apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
  - port: 5000            # Service port
    targetPort: 5000      # Port on the pod
    protocol: TCP
    nodePort: 30503       # NodePort assigned for external access
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  sessionAffinity: None
